/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_p8499_lang_ime_JniWrapper */

#ifndef _Included_com_p8499_lang_ime_JniWrapper
#define _Included_com_p8499_lang_ime_JniWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    startup
 * Signature: (Lcom/p8499/lang/ime/rime/RimeTraits;)V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_startup
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeSetup
  (JNIEnv *, jclass);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeInitialize
  (JNIEnv *, jclass);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeStartMaintenance
 * Signature: (Ljava/lang/Integer;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeStartMaintenance
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeJoinMaintenanceThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeJoinMaintenanceThread
  (JNIEnv *, jclass);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeConfigGetBool
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeConfigGetBool
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeConfigGetInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeConfigGetInt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeConfigGetDouble
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeConfigGetDouble
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeConfigGetString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeConfigGetString
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeConfigSetBool
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Integer;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeConfigSetBool
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeConfigSetInt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Integer;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeConfigSetInt
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeConfigSetDouble
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Double;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeConfigSetDouble
  (JNIEnv *, jclass, jstring, jstring, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeConfigSetString
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeConfigSetString
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetSchemaList
 * Signature: ()[Lcom/p8499/lang/ime/rime/RimeSchemaListItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetSchemaList
  (JNIEnv *, jclass);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeSelectSchema
 * Signature: (Ljava/lang/Long;Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeSelectSchema
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetModifierByName
 * Signature: (Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetModifierByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetModifierName
 * Signature: (Ljava/lang/Integer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetModifierName
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetKeycodeByName
 * Signature: (Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetKeycodeByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetKeyName
 * Signature: (Ljava/lang/Integer;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetKeyName
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeCreateSession
 * Signature: ()Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeCreateSession
  (JNIEnv *, jclass);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetStatus
 * Signature: (Ljava/lang/Long;)Lcom/p8499/lang/ime/rime/RimeStatus;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetStatus
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeSetOption
 * Signature: (Ljava/lang/Long;Ljava/lang/String;Ljava/lang/Integer;)V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeSetOption
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeProcessKey
 * Signature: (Ljava/lang/Long;Ljava/lang/Integer;Ljava/lang/Integer;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeProcessKey
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetContext
 * Signature: (Ljava/lang/Long;)Lcom/p8499/lang/ime/rime/RimeContext;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetContext
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetInput
 * Signature: (Ljava/lang/Long;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetInput
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetCaretPos
 * Signature: (Ljava/lang/Long;)Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetCaretPos
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeSetCaretPos
 * Signature: (Ljava/lang/Long;Ljava/lang/Long;)V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeSetCaretPos
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetAllCandidates
 * Signature: (Ljava/lang/Long;Ljava/lang/Integer;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetAllCandidates
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeSelectCandidate
 * Signature: (Ljava/lang/Long;Ljava/lang/Integer;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeSelectCandidate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeSelectCandidateOnCurrentPage
 * Signature: (Ljava/lang/Long;Ljava/lang/Integer;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeSelectCandidateOnCurrentPage
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeGetCommit
 * Signature: (Ljava/lang/Long;)Lcom/p8499/lang/ime/rime/RimeCommit;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeGetCommit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeDestroySession
 * Signature: (Ljava/lang/Long;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeDestroySession
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeCleanupStaleSessions
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeCleanupStaleSessions
  (JNIEnv *, jclass);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeCleanupAllSessions
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeCleanupAllSessions
  (JNIEnv *, jclass);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    rimeFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_rimeFinalize
  (JNIEnv *, jclass);

/*
 * Class:     com_p8499_lang_ime_JniWrapper
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_p8499_lang_ime_JniWrapper_shutdown
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
